### PR TITLE
Toonapi long lived access token

### PR DESCRIPTION
**Pull request by tljdebrouwer**
From December 1st, 2019. The current code grant flow is no longer support for eneco because of the login via mijn eneco.

This pull request allows the toonapi library to support long lived access token which can be generated.

### CODE REVIEW

**Comment by costastf** [comment]
Hi and thanks very much for the PR. Would you mind pointing me to the documentation that explains this change?

**Comment by tljdebrouwer** [comment]
Hi, the changes are described here https://developer.toon.eu/authentication

This is in combination with the change described here that "mijn eneco" users are required to login with "mijn eneco" from December 2019 onwards.

**Comment by tljdebrouwer** [comment]
@costastf Let me know if there is anything I can update on my PR? 

Would you have an idea what we need to do on the home assistant side to get this supported? I have some time to work on that as well.

**Comment by costastf** [comment]
Hi Tom,

Sorry for not picking this up yet, have been quite busy and I planned some
time next weekend for it. I need to check if the current authentication
will still work along with long running token. If it will then I want to
make a factory object that handles both ends with the proper toon object
based on the arguments passed to it (not passing in none for the
arguments). If the old authenticating will still working then we just have
one argument of token for the toon object. Depending on this the ha
component needs to be extended accordingly (drop the old arguments one only
have the token one or support all of them and have logic that filters them
accordingly.) I hope this makes sense and again thanks for your efforts and
short for not completing this.

Kind regards
Costas

**Comment by costastf** [comment]
It seems that since tomorrow the old authentication will no be supported any more so I have refactored the code to use only the new token one and cleaned up all old references so i will close this. Thank you very much @tljdebrouwer for contributing non the less. Will you pick up the Home Assistant component accordingly?

**Comment by tljdebrouwer** [comment]
Hi Costa, thanks for that! 

I will pick this up next week. There might be one thing to consider I think only Eneco is over to this new method. Are there other users of this library?

**Comment by costastf** [comment]
As far as the home assistant component is concerned,I think it's only eneco. The library did cater for some rebranded Spanish toons but the previous version should work just fine for those. I did try to implement the changes required for home assistant but did not finish and sadly will not have time, so if you want to pick it up please look at the branch I have on my github for it and start from there.

**Comment by costastf** [comment]
@tljdebrouwer https://github.com/costastf/home-assistant dev branch. It should be rebased to "next" branch of home assistant if you want to take over.

**Pull request closed without merging**
