### PR TITLE
Added support to change program_state

### PR DESCRIPTION
**Pull request by JohnvandeVrugt**
Includes a getter/setter for the program state.
This way one can enable/disable the automatic time based program of the Toon device.

### CODE REVIEW

**Comment by JohnvandeVrugt** [comment]
Not that familiar with github and forks; the commit that I wanted to be pulled was db7e48f.
By updating my fork, I have extra commits compared to your original repo.

**Review by costastf — CHANGES_REQUESTED** [review]
This is lovely, but not very useful if someone does not know the numbers and what they represent. I think it would be better to code this like the thermostat states, with names for the states so it is useful to anyone.

**Comment by costastf** [comment]
Oh, and since you are doing this, please also add yourself to the contributors on the header of the file and the CONTRIBUTORS.rst file :)

**Comment by JohnvandeVrugt** [comment]
Point taken; will try to create some meaningful enumerations.

**Comment by costastf** [comment]
May I also suggest you drop the thermostat prefix and just leave program? I think that it's pretty self explanatory.

**Comment by frenck** [comment]
Nice addition!

**Comment by JohnvandeVrugt** [comment]
I have created a new pull request.
Did not add myself to the contributers list. Too much honor :)

I assume you cannot reuse this pull request for a second attempt?

**Pull request closed without merging**
